name: Java CI with Maven + MongoDB + Coveralls
on:
  workflow_dispatch:  # <-- Adds "Run workflow" button on GitHub
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Build, Test & Generate Coverage
      run: mvn clean verify jacoco:report

    - name: Upload Coverage to Coveralls (no token needed)
      run: mvn coveralls:report
